### PR TITLE
Update es.json

### PR DESCRIPTION
**Pull request by davidsosa2022**
Some stuff fixed and "Geniales" was changed to "Me encanta"

### CODE REVIEW

**Comment by CirnoMoment** [comment]
Uh... I'm fairly certain if you have a translation issue, it's best to do it here: https://hosted.weblate.org/projects/pretendonetwork/ and not on the repo.

**Comment by ashmonty** [comment]
> Uh... I'm fairly certain if you have a translation issue, it's best to do it here: https://hosted.weblate.org/projects/pretendonetwork/ and not on the repo.

I can confirm that is exactly how you're supposed to do that

**Comment by DkStar7** [comment]
Por que cambiar "Genial" a "Me encanta"?

**Comment by DkStar7** [comment]
De hecho deberíamos usar "Mola" porque es la palabra que utilizo Nintendo en Miiverse

**Pull request closed without merging**
